Feat/header
bricksandbraces/webcomponents pull request #11
Opened 2022-02-04 13:46 UTC by klonsian

2022-02-05 17:16 UTC, hendriku requested changes

2022-02-05 17:16 UTC, hendriku commented on src/components/Header/Header.tsx
> +  const [open, setOpen] = useState(false);
Der state ist ja jetzt intern und nicht mehr von außen steuerbar. Meinst du es gibt Szenarien wo wir das doch noch brauchen? Aktuell kann sich der Header nur selber öffnen.

2022-02-05 17:16 UTC, hendriku commented on src/components/Hero/Hero.tsx
> +  const indexedCtaItems = idfy(ctaItems);
Kann entfernt werden, richtig?

2022-02-05 17:16 UTC, hendriku commented on src/components/Hero/Hero.tsx
> +  showChevron: boolean;
```suggestion
  showChevron?: boolean;
```

2022-02-06 21:12 UTC, klonsian commented on src/components/Header/Header.tsx
> +  const [open, setOpen] = useState(false);
wüsste aktuell nicht, welcher Case das sein könnte, wenn dir einer einfällt, können wir es ja noch nachsteuern - oder?

2022-02-06 21:12 UTC, klonsian commented on src/components/Hero/Hero.tsx
> +  const indexedCtaItems = idfy(ctaItems);
yes.

2022-02-06 21:13 UTC, klonsian commented on package.json
> +    "@openbricksandbraces/designsystem": "^0.0.3",
Hahahaha ne natürlich nicht, wie kommt das auf 0.0.3? :O Aktuell ist ja 0.1.1

2022-04-26 09:06 UTC, merged